#ifndef ___GESTIONG_CONTABLE_RECCONTRAPARTIDA_H
#define ___GESTIONG_CONTABLE_RECCONTRAPARTIDA_H

namespace gong {
typedef RecCuenta RecContrapartida;
}

#endif // ___GESTIONG_CONTABLE_RECCONTRAPARTIDA_H
