# Script para actualizar el stocks de los artículos

UPDATE ARTICULO SET STOCK = 0.0;

# Suma Albaranes de compra, sin facturar

UPDATE ARTICULO A
SET STOCK = STOCK + COALESCE(
(SELECT COALESCE(SUM(CANTIDAD),0) FROM ALBARANCOMPRADET
INNER JOIN ALBARANCOMPRA ON ALBARANCOMPRADET.ALBARANCOMPRA_ID = ALBARANCOMPRA.ID AND ALBARANCOMPRA.FACTURADO=0
INNER JOIN TIPODOC T ON T.ID = ALBARANCOMPRA.TIPODOC_ID AND T.ACTUALIZASTOCKS = 1
WHERE ALBARANCOMPRADET.ARTICULO_ID = A.ID
GROUP BY ALBARANCOMPRADET.ARTICULO_ID), 0 )
WHERE A.USARSTOCKS = 1;

# Suma Facturas de compra, incluye albaranes facturados

UPDATE ARTICULO A
SET STOCK = STOCK + COALESCE(
(SELECT COALESCE(SUM(CANTIDAD),0) FROM FACTURACOMPRADET
INNER JOIN FACTURACOMPRA ON FACTURACOMPRADET.FACTURACOMPRA_ID = FACTURACOMPRA.ID
INNER JOIN TIPODOC T ON T.ID = FACTURACOMPRA.TIPODOC_ID AND T.ACTUALIZASTOCKS = 1
WHERE FACTURACOMPRADET.ARTICULO_ID = A.ID
GROUP BY FACTURACOMPRADET.ARTICULO_ID),0)
WHERE A.USARSTOCKS = 1;

# Resta Albaranes de venta, sin facturar

UPDATE ARTICULO A
SET STOCK = STOCK - COALESCE(
(SELECT COALESCE(SUM(CANTIDAD),0) FROM ALBARANVENTADET
INNER JOIN ALBARANVENTA ON ALBARANVENTADET.ALBARANVENTA_ID = ALBARANVENTA.ID AND ALBARANVENTA.FACTURADO=0
INNER JOIN TIPODOC T ON T.ID = ALBARANVENTA.TIPODOC_ID AND T.ACTUALIZASTOCKS = 1
WHERE ALBARANVENTADET.ARTICULO_ID = A.ID
GROUP BY ALBARANVENTADET.ARTICULO_ID), 0)
WHERE A.USARSTOCKS = 1;

# Resta Facturas de venta, incluye albaranes facturados

UPDATE ARTICULO A
SET STOCK = STOCK - COALESCE(
(SELECT COALESCE(SUM(CANTIDAD),0) FROM FACTURAVENTADET
INNER JOIN FACTURAVENTA ON FACTURAVENTADET.FACTURAVENTA_ID = FACTURAVENTA.ID
INNER JOIN TIPODOC T ON T.ID = FACTURAVENTA.TIPODOC_ID AND T.ACTUALIZASTOCKS = 1
WHERE FACTURAVENTADET.ARTICULO_ID = A.ID
GROUP BY FACTURAVENTADET.ARTICULO_ID), 0)
WHERE A.USARSTOCKS = 1;
